### ISSUE TITLE
Noteworthy in Classic_ERA opacity broken

### ISSUE THREAD

**Issue by Torqueitup** [28/NoteworthyII#4]
Hi,
The opacity of the dropdown panels opacity is broken - there is no shading at all thus I can see all the screen behind the dropdown panels.  This has occurred on alot of addons recently with Blizz's update
![image](https://user-images.githubusercontent.com/91725389/136758025-737f0ef7-8a6b-4102-ad4a-4d6d209db83b.png)

**Comment by 28** [comment]
Indeed, Blizz switched to the new Backdrop API.

I have fixed it in Noteworthy II. Version 2.3.2 should be available soon. Please update and check again.
Thanks!

**Comment by Torqueitup** [comment]
All good, downloaded the latest version and ran it.  Back on track.  Thanks
for fixing it.

**Comment by 28** [comment]
Great!
Have a good one!
