### ISSUE TITLE
Option to remove chat notification upon logging in

### ISSUE THREAD

**Issue by Rezy942** [28/NoteworthyII#6]
Hello,

Thank you for lovely addon
Can we please get an option (or remove entirely) the chat notification on every login / reload?
A lot of users like me enjoy minimalistic non-spam UI. I dont think this will be missed as we really have no use for this info.
(everyone i know just uses minimap buttons, and if the point is explaining the slash command, then perhaps it can be shown somewhere else?)
![image](https://user-images.githubusercontent.com/122007087/229700502-066722cd-a025-457e-8a2b-b14ecf228397.png)

Thank you :)

**Comment by Rezy942** [comment]
Thank you so much!!

**Comment by 28** [comment]
This is now implemented in version 2.4.5.
Check it out. :-)
Thanks again for reporting.
