### ISSUE TITLE
Minor modification request: window strata (perhaps optional)

### ISSUE THREAD

**Issue by Rezy942** [28/NoteworthyII#7]
Could we raise the strata of main window so it is on top of all other windows?
Or perhaps an option for this?
(by default i feel like window should be at the very top of all other windows)
![image](https://user-images.githubusercontent.com/122007087/230500117-1012155f-9309-49f9-ba47-4c99b9712b24.png)

Thanks :)

**Comment by 28** [comment]
Hi,
This is a good suggestion. I will see what can be done.
Thanks again!

**Comment by 28** [comment]
This is now implemented in version 2.4.5.
Check it out. :-)
Thanks again for reporting.

**Comment by Rezy942** [comment]
Thanks!!!!
