### ISSUE TITLE
Feature Request: allow window scale option

### ISSUE THREAD

**Issue by ghost** [28/NoteworthyII#8]
Hello,

Would this be possible?
The window is a bit too large for me, especially on my ultrawide screen :)
It looks gigantic compared to everything else

Thanks!!

**Comment by 28** [comment]
Hi,

I can't make any promises about scaling. It is a very reasonable feature, but it may be a little bit much work given the state the codebase is in right now.

Can you provide a screenshot? I would like to see the size disproportions on ultrawide.

Thanks!

**Comment by Rezy942** [comment]
Alright I see, its not a huge issue, i can live without it :)
Just would like more real estate for example when I have auction and bag windows open, i use notes a lot for purchasing stuff as a "shopping list"!

Example:
![image](https://github.com/28/NoteworthyII/assets/122007087/2933b30f-e95a-4021-b97c-8391872deea6)
